"""SheetContentGenerator - Deterministic spreadsheet generation (no LLM)."""
from __future__ import annotations

from typing import Any

from ..schemas import SheetColumn, SheetRow, SheetSpec


class SheetContentGenerator:
    """
    Deterministic generator that produces SheetSpec from supply chain data.
    No LLM calls — pure data transformation.
    """

    def generate(
        self,
        template: str,
        data_context: dict[str, Any],
    ) -> SheetSpec:
        """
        Generate a SheetSpec based on the template.

        Args:
            template: Template name (inventory_status, demand_accuracy, etc.)
            data_context: Supply chain data context.

        Returns:
            SheetSpec with columns, rows, and optional summary/notes.
        """
        generator_map = {
            "inventory_status": self._inventory_status,
            "demand_accuracy": self._demand_accuracy,
            "replenishment_plan": self._replenishment_plan,
            "supplier_scorecard": self._supplier_scorecard,
        }

        generator = generator_map.get(template, self._inventory_status)
        return generator(data_context)

    # ─── Template: Inventory Status ───────────────────────────────────────

    def _inventory_status(self, data_context: dict[str, Any]) -> SheetSpec:
        columns = [
            SheetColumn(header="SKU", width=30, data_type="string"),
            SheetColumn(header="Category", width=18, data_type="string"),
            SheetColumn(header="Warehouse", width=22, data_type="string"),
            SheetColumn(header="Available Stock", width=16, data_type="number"),
            SheetColumn(header="Days of Supply", width=16, data_type="number"),
            SheetColumn(header="Risk Level", width=14, data_type="string"),
            SheetColumn(header="In Transit", width=14, data_type="number"),
        ]

        rows: list[SheetRow] = []
        inventory = data_context.get("inventory", [])

        for item in inventory:
            i = item.model_dump() if hasattr(item, "model_dump") else item
            risk = i.get("risk_level", "")
            risk_val = risk.value if hasattr(risk, "value") else str(risk)
            cat = i.get("category", "")
            cat_val = cat.value if hasattr(cat, "value") else str(cat)

            highlight = self._risk_to_highlight(risk_val)

            rows.append(SheetRow(
                values=[
                    str(i.get("sku_name", "")),
                    cat_val,
                    str(i.get("warehouse", "")),
                    str(i.get("available_stock", 0)),
                    str(round(i.get("days_of_supply", 0), 1)),
                    risk_val.capitalize(),
                    str(i.get("in_transit", 0)),
                ],
                highlight=highlight,
            ))

        # Summary row
        total_stock = sum(
            _safe_float(item, "available_stock") for item in inventory
        )
        avg_dos = (
            sum(_safe_float(item, "days_of_supply") for item in inventory) / len(inventory)
            if inventory else 0
        )
        summary_row = [
            "TOTAL / AVG",
            "",
            "",
            str(round(total_stock)),
            str(round(avg_dos, 1)),
            "",
            str(round(sum(_safe_float(item, "in_transit") for item in inventory))),
        ]

        critical_count = sum(1 for item in inventory if _get_field(item, "risk_level") == "critical")
        warning_count = sum(1 for item in inventory if _get_field(item, "risk_level") == "warning")

        notes = [
            f"Total SKUs: {len(inventory)}",
            f"Critical risk items: {critical_count}",
            f"Warning risk items: {warning_count}",
            "Generated by Atlas AI — Héroux-Devtek Inc.",
        ]

        return SheetSpec(
            title="Inventory Status Report",
            sheet_name="Inventory",
            columns=columns,
            rows=rows,
            summary_row=summary_row,
            notes=notes,
        )

    # ─── Template: Demand Accuracy ────────────────────────────────────────

    def _demand_accuracy(self, data_context: dict[str, Any]) -> SheetSpec:
        columns = [
            SheetColumn(header="SKU", width=28, data_type="string"),
            SheetColumn(header="Week", width=14, data_type="string"),
            SheetColumn(header="Forecast", width=14, data_type="number"),
            SheetColumn(header="Lower 80%", width=14, data_type="number"),
            SheetColumn(header="Upper 80%", width=14, data_type="number"),
            SheetColumn(header="Range %", width=12, data_type="percent"),
        ]

        rows: list[SheetRow] = []
        forecasts = data_context.get("forecasts", [])

        for fc in forecasts:
            f = fc.model_dump() if hasattr(fc, "model_dump") else fc
            point = f.get("point_forecast", 0)
            lower = f.get("lower_80", 0)
            upper = f.get("upper_80", 0)

            # Range % = (upper - lower) / point * 100
            range_pct = ((upper - lower) / point * 100) if point > 0 else 0

            # Highlight by range width: wide range = less certain
            if range_pct > 40:
                highlight = "red"
            elif range_pct > 25:
                highlight = "yellow"
            else:
                highlight = "none"

            rows.append(SheetRow(
                values=[
                    str(f.get("sku_name", f.get("sku_id", ""))),
                    str(f.get("week", "")),
                    str(round(point)),
                    str(round(lower)),
                    str(round(upper)),
                    f"{range_pct:.1f}%",
                ],
                highlight=highlight,
            ))

        notes = [
            f"Total forecast records: {len(forecasts)}",
            "Range % = (Upper 80 - Lower 80) / Point Forecast * 100",
            "Red: Range > 40%, Yellow: Range > 25%",
            "Generated by Atlas AI — Héroux-Devtek Inc.",
        ]

        return SheetSpec(
            title="Demand Forecast Accuracy Report",
            sheet_name="Demand Accuracy",
            columns=columns,
            rows=rows,
            summary_row=None,
            notes=notes,
        )

    # ─── Template: Replenishment Plan ─────────────────────────────────────

    def _replenishment_plan(self, data_context: dict[str, Any]) -> SheetSpec:
        columns = [
            SheetColumn(header="SKU", width=28, data_type="string"),
            SheetColumn(header="Action Type", width=18, data_type="string"),
            SheetColumn(header="Recommended Qty", width=18, data_type="number"),
            SheetColumn(header="Urgency", width=14, data_type="string"),
            SheetColumn(header="Confidence", width=14, data_type="string"),
            SheetColumn(header="Scenario", width=18, data_type="string"),
        ]

        rows: list[SheetRow] = []
        actions = data_context.get("actions", [])

        for act in actions:
            a = act.model_dump() if hasattr(act, "model_dump") else act
            urgency = str(a.get("urgency", "")).lower()

            # Highlight by urgency
            if urgency in ("critical", "high"):
                highlight = "red"
            elif urgency == "medium":
                highlight = "yellow"
            else:
                highlight = "none"

            rows.append(SheetRow(
                values=[
                    str(a.get("sku_name", "")),
                    str(a.get("action_type", "")),
                    str(round(a.get("recommended_qty", 0))),
                    urgency.capitalize(),
                    str(a.get("confidence", "")),
                    str(a.get("scenario", "")),
                ],
                highlight=highlight,
            ))

        total_qty = sum(_safe_float(act, "recommended_qty") for act in actions)
        critical_count = sum(
            1 for act in actions
            if str(_get_field(act, "urgency")).lower() in ("critical", "high")
        )

        notes = [
            f"Total actions: {len(actions)}",
            f"Critical/High urgency: {critical_count}",
            f"Total recommended quantity: {round(total_qty):,}",
            "Generated by Atlas AI — Héroux-Devtek Inc.",
        ]

        return SheetSpec(
            title="Replenishment Action Plan",
            sheet_name="Replenishment",
            columns=columns,
            rows=rows,
            summary_row=None,
            notes=notes,
        )

    # ─── Template: Supplier Scorecard ─────────────────────────────────────

    def _supplier_scorecard(self, data_context: dict[str, Any]) -> SheetSpec:
        columns = [
            SheetColumn(header="Supplier", width=28, data_type="string"),
            SheetColumn(header="Country", width=16, data_type="string"),
            SheetColumn(header="Avg Lead Time", width=16, data_type="number"),
            SheetColumn(header="Reliability %", width=16, data_type="percent"),
            SheetColumn(header="Quality Score", width=16, data_type="number"),
            SheetColumn(header="Active Orders", width=16, data_type="number"),
        ]

        rows: list[SheetRow] = []
        suppliers = data_context.get("suppliers", [])

        for sup in suppliers:
            s = sup.model_dump() if hasattr(sup, "model_dump") else sup
            reliability = s.get("reliability_score", 0)

            # Highlight by reliability: low reliability = concerning
            if reliability < 0.80:
                highlight = "red"
            elif reliability < 0.90:
                highlight = "yellow"
            else:
                highlight = "green"

            rows.append(SheetRow(
                values=[
                    str(s.get("name", "")),
                    str(s.get("country", "")),
                    str(s.get("avg_lead_time_days", "")),
                    f"{reliability * 100:.1f}%",
                    f"{s.get('quality_score', 0):.2f}",
                    str(s.get("current_orders", 0)),
                ],
                highlight=highlight,
            ))

        notes = [
            f"Total suppliers: {len(suppliers)}",
            "Red: Reliability < 80%, Yellow: < 90%, Green: >= 90%",
            "Generated by Atlas AI — Héroux-Devtek Inc.",
        ]

        return SheetSpec(
            title="Supplier Performance Scorecard",
            sheet_name="Suppliers",
            columns=columns,
            rows=rows,
            summary_row=None,
            notes=notes,
        )

    # ─── Helpers ──────────────────────────────────────────────────────────

    @staticmethod
    def _risk_to_highlight(risk: str) -> str:
        """Map risk level to highlight color."""
        risk_lower = risk.lower()
        if risk_lower == "critical":
            return "red"
        elif risk_lower == "warning":
            return "yellow"
        elif risk_lower == "excess":
            return "yellow"
        return "none"


# ─── Module-level helpers ─────────────────────────────────────────────────────

def _safe_float(item: Any, field: str) -> float:
    """Safely extract a numeric field from a model or dict."""
    if isinstance(item, dict):
        val = item.get(field, 0)
    elif hasattr(item, field):
        val = getattr(item, field, 0)
    else:
        return 0.0
    try:
        return float(val)
    except (TypeError, ValueError):
        return 0.0


def _get_field(item: Any, field: str) -> str:
    """Safely extract a string field from a model or dict."""
    if isinstance(item, dict):
        val = item.get(field, "")
    elif hasattr(item, field):
        val = getattr(item, field, "")
    else:
        return ""
    if hasattr(val, "value"):
        return val.value
    return str(val).lower()
